name: is_it_poisonous
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cross_file: ^0.3.4+2
  csv: ^6.0.0
  flutter:
    sdk: flutter
  flutter_onnxruntime: ^1.4.1
  image: ^4.5.4
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/model.mp3
    - assets/csv/species.csv